### ISSUE TITLE
Set up pre-commit hooks.

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/networkx-to-lava-nc#3]
Include pre-commit hook:
https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

After looking into this example:
https://github.com/EdgarLefevre/python_cookiecutter/blob/fd033120be724027e52e5596c0c9cd5093f7db59/%7B%7Bcookiecutter.directory_name%7D%7D/.pre-commit-config.yaml
I determined it would be of added  value to also include the following pre-commit checks for Python:
- [x] instead, use: https://pypi.org/project/isort/ (sorts the imports alphabetically)
- [x] Use: https://github.com/python/mypy for static type checking.
Also, check if you can include the coverage:
```
#-   repo: local
#    hooks:
#    -   id: run_test
#        name: "Run Pytest"
#        entry: "python .run_pytest.py"
#        language: "conda"
#        types: [python]
#    -   id: check_coverage
#        name: "Check Coverage"
#        entry: "python .check_coverage.py"
#        language: "conda"
#        types: [python]
```
Below are more pre-commit hook checks that can be included:
- [x] list them, evaluate them, and decide if you want them. If yes, implement them.
https://github.com/mozilla/code-coverage/blob/master/.pre-commit-config.yaml

Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Failed

**Comment by a-t-0** [comment]
black....................................................................Passed
blacken-docs.........................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Flake8...................................................................Passed
Reorder python imports...................................................Passed
pyupgrade................................................................Passed
rst ``code`` is two backticks........................(no files to check)Skipped
rst..................................................(no files to check)Skipped
changelog filenames..................................(no files to check)Skipped

**Comment by a-t-0** [comment]
- [ ] There are also default checks created by the `pre-commit` software package. These are listed [here](https://github.com/pre-commit/pre-commit-hooks/tree/main/pre_commit_hooks). They can be included in the `.pre-commit-config.yaml` file with:
```
 - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
      - id: name-tests-test
        args: ['--django']
      - id: check-json
      - id: requirements-txt-fixer
  ```

**Comment by a-t-0** [comment]
After evaluating: https://github.com/mozilla/code-coverage/blob/master/.pre-commit-config.yaml
Don't implement:
taskcluster, it is a CI service, yet we host our own GitLab-CI and have not found reason yet to adapt.
yesqa seems to be removing noqa statments. the noqa statements seem to be used to "skip quality assurance" and sometimes the may be forgottn to be removed even if the temporary qa issue has been resolved, in that case the yesqa removes the noqa in the code. We don't want to use noqa, because we want all code to submit to QA.

**Comment by a-t-0** [comment]
Include pylint

**Comment by a-t-0** [comment]
```
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
    hooks:
      - id: commitizen
        stages: [commit-msg]


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: prettier

-   repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports", "--recursive"]
        name: AutoFlake
        description: "Format with AutoFlake"
        stages: [commit]


-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -  id: bandit
       name: Bandit
       stages: [commit]

- repo: https://github.com/executablebooks/mdformat
  rev: b8c05ae822d53326e967da45367d0408afc56a81  # frozen: 0.7.14
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-toc
    - mdformat-gfm
    - mdformat-black

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: 1683a63d850e065495c05b771e4a20db010a58e7  # frozen: v0.3.1
  hooks:
  - id: absolufy-imports
    files: '^src/.+\.py$'
    args: ['--never', '--application-directories', 'src']

- repo: https://github.com/myint/docformatter
  rev: 67919ee01837761f2d954d7fbb08c12cdd38ec5a  # frozen: v1.4
  hooks:
  - id: docformatter


- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]


  # linters
  - repo: https://github.com/compwa/mirrors-pyright
    rev: "v1.1.244"
    hooks:
      - id: pyright
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint


  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-absolute-import
          - flake8-annotations
          - flake8-bandit
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-eradicate
          - flake8-no-pep420
          - flake8-pie
          - flake8-print
          - flake8-simplify
          - flake8-unused-arguments                        
```
